# fly.toml app configuration file generated for flask-app-bold-sound-4625 on 2024-12-09T13:48:47-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'flask-app-bold-sound-4625'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
